name: Upload to Chrome web store

on:
  push:
    tags:
      - 'v*.*.*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Upload new package
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      deployments: write
    steps:
      #
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Yarn
        run: npm install -g yarn@2

      # - name: Install dependencies
      #   run: yarn install
      - name: Cache CDK Dependencies
        uses: actions/cache@v3
        id: cache_cdk_dependency_id
        env:
          cache-name: cache-cdk-dependency
        with:
          path: .yarn/cache # node_modulesに代えて.yarn/cacheをキャッシュする
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install Dependencies
        if: ${{ steps.cache_cdk_dependency_id.outputs.cache-hit != 'true' }}
        run: yarn --immutable --immutable-cache

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      # - name: Set version
      #   id: version
      #   run: |
      #     REPOSITORY=$(echo ${{ github.repository }} | sed -e "s#.*/##")
      #     VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
      #     echo ::set-output name=version::$VERSION
      #     echo ::set-output name=filename::$REPOSITORY-$VERSION

      - name: Archive
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r release.zip dist

      - name: Upload to Chrome Web Store
        uses: mobilefirstllc/cws-publish@latest
        with:
          action: 'upload' # one of: upload, publish, testers
          client_id: ${{ secrets.CWS_API_CLIENT_ID }}
          client_secret: ${{ secrets.CWS_API_CLIENT_SECRET }}
          refresh_token: ${{ secrets.CWS_API_REFRESH_TOKEN }}
          extension_id: 'mmknldkcmcahihdpdeljnjgjclkbcldm'
          zip_file: release.zip
